### ISSUE TITLE
js向服务器传输json字符串中包含中文出错

### ISSUE THREAD

**Issue by dawnBefore** [walkor/web-msg-sender#10]
请问如何解决呢？

**Comment by walkor** [comment]
一般是网页不是utf8编码导致的。
网页文件本身要utf8编码，并且网页charset="utf-8"

**Comment by dawnBefore** [comment]
我用的是chrome 编码是UTF-8， charset也是UTF-8,  传输中文的时候会卡住，服务器端的代码不会执行，我现在采用的是转Unicode编码，这种做法感觉不太好？

**Comment by walkor** [comment]
先不要集成在你的网页里，
试下这个demo是否有问题

**Comment by dawnBefore** [comment]
好的，我试下

**Comment by dawnBefore** [comment]
还是不行，简单的放在我的网页里试了下，传中文还是有错

**Comment by walkor** [comment]
我的意思是你先不要集成在你的网页里，什么也不要改，试下demo有没有问题。

或者你干脆测试下 http://www.workerman.net:2123/ 看看是否有问题。

**Comment by dawnBefore** [comment]
sorry, 我是个php新手，我只会放在网页中测试...我再研究下吧
