### ISSUE TITLE
请问支持 https 站点么？ socket 是否也支持 wss协议

### ISSUE THREAD

**Issue by iMactool** [walkor/web-msg-sender#11]
请问支持 https 站点么？ socket 是否也支持 wss协议

**Comment by walkor** [comment]
支持。
参考phpsocket.io手册
https://github.com/walkor/phpsocket.io/tree/master/docs/zh#支持sslhttps-wss

**Comment by wakerman** [comment]
Worker好像不支持 https协议 ?  http://doc.workerman.net/315128 
![image](https://user-images.githubusercontent.com/3078413/28204230-b14c8c7e-68af-11e7-90bc-5538a6908172.png)
只有http请求可以通过（因为整站都是https的，如果worker 用 http 会不会有什么影响么？）。
![image](https://user-images.githubusercontent.com/3078413/28204250-cf4f238a-68af-11e7-859c-13d3c425aef5.png)

**Comment by walkor** [comment]
参考workerman手册 http://doc.workerman.net/315298

**Comment by wakerman** [comment]
感谢抽空回复。

**Comment by wakerman** [comment]
后端调用api向任意用户推送：
<?php
// 指明给谁推送，为空表示向所有在线用户推送
$to_uid = "";
// 推送的url地址，使用自己的服务器地址
$push_api_url = "http://workerman.net:2121/";
$post_data = array(
   "type" => "publish",
   "content" => "这个是推送的测试数据",
   "to" => $to_uid, 
);

  这里 ` "to" => $to_uid, ` 只能接收 一个uid的值 ？如果要发送给多个人尼？ 而且好像（$_POST）只能发送和接收 type,content,to这三个值。

**Comment by walkor** [comment]
可以传多个，自己foreach 发就行了。
你这个问题自己稍微改下代码就ok了

**Comment by wakerman** [comment]
发送多人的 foreach 了
```
if(is_array($to)){
	 foreach ($to as $toid){
		 $io->to($toid)->emit('new msg',$_POST['content']);
	 }
	 }else{
	     $io->to($to)->emit('new msg',$_POST['content']);
	 }
```
，这个多添加的参数没找到在哪个文件里修改。
直接用这样方式了
![image](https://user-images.githubusercontent.com/3078413/28261498-1dadc6ee-6b12-11e7-848c-5ab17e49f9a3.png)

看着有点别扭 :(
