### ISSUE TITLE
只允许指定用户连接？

### ISSUE THREAD

**Issue by markyong** [walkor/web-msg-sender#12]
HI，如果说需要只允许指定客户端连接服务端，框架有实现这个功能的吗？谢谢

**Comment by walkor** [comment]
web-msg-sender没实现这个功能。

**Comment by markyong** [comment]
哦，框架很棒！可以考虑在前端连接时加个鉴权的功能！

**Comment by walkor** [comment]
鉴权自己做就行了，根据用户名密码查数据库，验证token等都可以，自由选择空间很大。写死了或者复杂了反而不好。并且绝大部分用户不需要此功能。

**Comment by markyong** [comment]
嗯嗯，thank you
