### ISSUE TITLE
workerman运行一段时间后会自动关闭，cron定时重启无效

### ISSUE THREAD

**Issue by aqnaruto** [walkor/web-msg-sender#15]
我的workerman是单独运行的，但是机器上同时有nginx的php服务，
不知是否是干扰问题，每运行十几个小时候会自动关闭。
我在cron里加了定时重启，但是后台定时重启无效，每次我手动去重启才恢复正常

![image](https://user-images.githubusercontent.com/9067159/34904424-7e56a348-f880-11e7-9584-a71c62143a41.png)

以上是cron的log，难道这样加错了吗？还是这样根本无效

**Comment by walkor** [comment]
用 daemon方式运行，不会关闭

**Comment by aqnaruto** [comment]
php start.php start -d 吗 好的 谢谢您 我试试 在观察一下，话说 之前我部署在宁一台服务器的时候 是不会自动关闭的，当前这台服务器上有nginx的php-fpm跑一些网页 我怀疑是影响到了。再次感谢您，我先用daemon方式继续观察一下
