### ISSUE TITLE
请问有没有post数据的验证措施?比如只能在运行服务的服务器上发送数据

### ISSUE THREAD

**Issue by chn-yang** [walkor/web-msg-sender#17]
我在我的服务器运行了服务之后,并且跑通了demo, 
然后把测试的post代码放到我的本地windows php cli运行一下,一样可以发送消息, 
也就是只要有域名,端口默认,知道用户id或者随便乱输用户Id的话, 任何人都可以用php脚本post数据的

**Comment by walkor** [comment]
可以把内部端口只开放给内网，比如设置安全组或者防火墙，比如内部监听设置成监听127.0.0.1 。
也可以自己做个验证机制，简单的比如验证一个token串等

**Comment by chn-yang** [comment]
为了方便像我一样的小白, 在这里给出我提出的issue目前个人能做到的解决方法

如果有不对的地方,请各位大佬指正

start_io.php由
```PHP
$inner_http_worker = new Worker('http://0.0.0.0:2121');
```
改为
```PHP
$inner_http_worker = new Worker('http://127.0.0.1:2121');
```

防火墙添加
```BASH
/sbin/iptables -I INPUT -p tcp --dport 2120 -j ACCEPT
/sbin/iptables -I INPUT -p tcp --dport 2123 -j ACCEPT
```
不要添加
```BASH
/sbin/iptables -I INPUT -p tcp --dport 2121 -j ACCEPT
```
