### ISSUE TITLE
socket.io-clientpp无法完成链接

### ISSUE THREAD

**Issue by KinderLi** [walkor/web-msg-sender#5]
使用socket.io-clientpp开发的客户端，在与服务进行http链接后，等待ws链接时显示超时；
用js的client没问题。java，c++的都有问题。但连socket.io的服务器正常。

**Comment by walkor** [comment]
socket.io-clientpp 库太老了，最近更新是4年前。socket.io-clientpp 只支持到0.8

PHPSocket.io不支持老版本。

**Comment by KinderLi** [comment]
C++的版本，除了socket.io-clientpp ，还有其他的推荐吗？

**Comment by KinderLi** [comment]
另外，我看到socket.io-clientpp 最近一次release是0.7,不知0.8的版本是指？

**Comment by walkor** [comment]
> This project has not been tested with anything after Socket.IO 0.8.

Readme里面说的。

C++版本可以github上再找一下，我这没有研究过

**Comment by KinderLi** [comment]
发现一个新的现象：

**Comment by KinderLi** [comment]
我用socket.io的js库写一个server。然后用js，C++，java的客户端去连，都正常。

**Comment by KinderLi** [comment]
但是连phpsocket.io的，就只有js的可以。是socket.io有兼容代码？phpsocket.io把这些兼容代码忽略了，没有实现？

**Comment by walkor** [comment]
phpsocket.io是参照socket.io 1.3.0 版本写的，phpsocket.io不能保证和每个客户端都兼容。

**Comment by KinderLi** [comment]
明白，谢谢。我在研究一下吧。
