### ISSUE TITLE
discuss

### ISSUE THREAD

**Issue by sundylink** [walkor/web-msg-sender#8]
这个框架对于前端就是引入socket.io.js，两行代码就实现消息推送系统，另外浏览器兼容性如何？长连接推送（websocket或者comet这个主要是scoket.io做的兼容？

**Comment by walkor** [comment]
socket.io是一个非常有名的web即时通讯框架，浏览器兼容性做的可以说是最好的，在浏览器不支持websocket时自动转为comet。socket.io需要客户端和服务端配合才能发挥作用。

socket.io服务端是默认是nodejs的，世界上一直没有可用的php版本socket.io服务端，workerman在15年9月份推出了php版本 [phpsocket.io](https://github.com/walkor/phpsocket.io)，web-msg-sender就是基于phpsocket.io开发的，继承了socket.io原有的超强的浏览器兼容性，同时也具备php的灵活简单的特性。

**Comment by sundyxfan** [comment]
java可实现scoket.io服务端？

**Comment by sundylink** [comment]
java 实现一版socket.io服务端

**Comment by walkor** [comment]
socket.io客户端版本很多，java c/c++ c# js swift objectc等都有，github上搜下就知道了。
选择时需要注意需要支持nodejs.1.3.0以上的才行。phpsocket.io只支持nodejs 1.3.0以上的版本
